rCREATE DATABASE quanlynhathuoc;
USE quanlynhathuoc;

-- Tạo bảng NHANVIEN trước (vì nhiều bảng khác tham chiếu đến NHANVIEN)
CREATE TABLE NHANVIEN(
  ID VARCHAR(50) PRIMARY KEY,
  TEN VARCHAR(50) NOT NULL,
  CHUCVU VARCHAR(50) NOT NULL,
  SDT VARCHAR(50) NOT NULL,
  DIACHI VARCHAR(50) NOT NULL
);

-- Tạo bảng TAIKHOAN (tham chiếu đến NHANVIEN)
CREATE TABLE TAIKHOAN(
  TK VARCHAR(50) PRIMARY KEY,
  MK VARCHAR(50) NOT NULL,
  IDNV VARCHAR(50) NOT NULL,
  FOREIGN KEY(IDNV) REFERENCES NHANVIEN(ID)
);

-- KHÁCH HÀNG (HOADONBAN sẽ tham chiếu tới bảng này)
CREATE TABLE KHACHHANG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TEN VARCHAR(50) NOT NULL,
  SDT VARCHAR(15) NOT NULL,
  POINT INT DEFAULT 0
);

-- NHÀ CUNG CẤP (HOADONNHAPHANG sẽ tham chiếu tới bảng này)
CREATE TABLE NHACUNGCAP(
  ID VARCHAR(50) PRIMARY KEY,
  TEN VARCHAR(50) NOT NULL,
  DIACHI VARCHAR(50),
  SDT VARCHAR(15) NOT NULL
);

-- SẢN PHẨM (nhiều bảng khác cần tham chiếu, nên tạo sớm)
CREATE TABLE SANPHAM(
  ID VARCHAR(20) PRIMARY KEY,
  TEN VARCHAR(30) NOT NULL,
  LOAI ENUM(
    'Kháng sinh',
    'thuốc giảm đau',
    'vitamin',
    'thực phẩm chức năng',
    'thuốc kháng virus',
    'thuốc tim mạch',
    'thuốc dị ứng',
    'thuốc hô hấp'
  ) NOT NULL,
  SOLUONG INT NOT NULL,
  GIANHAP DECIMAL(10,2) NOT NULL,
  GIABAN DECIMAL(10,2) NOT NULL,
  THANHPHAN VARCHAR(50),
  HAMLUONG VARCHAR(50),
  CONGDUNG VARCHAR(50),
  CACHDUNG VARCHAR(200),
  CHUY VARCHAR(200),       -- Có thể đổi tên thành NOTE hoặc CHU_Y để rõ nghĩa hơn
  HANSUDUNG DATE NOT NULL
);

-- HÓA ĐƠN NHẬP HÀNG (tham chiếu đến NHACUNGCAP)
CREATE TABLE HOADONNHAPHANG(
  ID VARCHAR(50) PRIMARY KEY,
  NGAYNHAP DATE NOT NULL,
  IDNCC VARCHAR(50),
  TONGTIEN DECIMAL(10,2) DEFAULT 0,
  PHUONGTHUCTHANHTOAN ENUM('Tien Mat', 'Chuyen Khoan'),
  FOREIGN KEY (IDNCC) REFERENCES NHACUNGCAP(ID)
);

-- CHI TIẾT NHẬP HÀNG (tham chiếu đến HOADONNHAPHANG và SANPHAM)
CREATE TABLE CHITIETNHAPHANG(
  ID VARCHAR(50) PRIMARY KEY,
  IDDNH VARCHAR(50),
  IDSP VARCHAR(50),
  SOLUONG INT NOT NULL,
  GIANHAP DECIMAL(10,2),
  FOREIGN KEY (IDSP) REFERENCES SANPHAM(ID),
  FOREIGN KEY (IDDNH) REFERENCES HOADONNHAPHANG(ID)
);

-- HÓA ĐƠN BÁN (tham chiếu đến KHÁCHHÀNG)
CREATE TABLE HOADONBAN(
  ID VARCHAR(20) PRIMARY KEY,
  NGAYMUA DATE NOT NULL,
  IDKHACHHANG INT,
  TONGTIEN DECIMAL(10,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (IDKHACHHANG) REFERENCES KHACHHANG(ID)
);

-- CHI TIẾT HÓA ĐƠN BÁN (tham chiếu đến HÓA ĐƠN BÁN và SẢN PHẨM)
CREATE TABLE CHITIETHOADON(
  ID VARCHAR(50) PRIMARY KEY,
  IDHD VARCHAR(50),
  IDSP VARCHAR(50),
  SOLUONG INT NOT NULL DEFAULT 1,
  FOREIGN KEY (IDSP) REFERENCES SANPHAM(ID),
  FOREIGN KEY (IDHD) REFERENCES HOADONBAN(ID)
);

-- THANH TOÁN (tham chiếu đến HÓA ĐƠN BÁN)
CREATE TABLE THANHTOAN(
  ID VARCHAR(50) PRIMARY KEY,
  IDHD VARCHAR(50),
  TRANGTHAI ENUM('đã thanh toán', 'đã hủy đơn') NOT NULL,
  PHUONGTHUCTHANHTOAN ENUM('chuyển khoản', 'tiền mặt') NOT NULL,
  FOREIGN KEY (IDHD) REFERENCES HOADONBAN(ID)
);

-- LỊCH LÀM (tham chiếu đến NHÂN VIÊN)
CREATE TABLE LICHLAM(
  ID VARCHAR(50) PRIMARY KEY,
  IDNV VARCHAR(50),
  NGAYLAM DATE NOT NULL,
  FOREIGN KEY (IDNV) REFERENCES NHANVIEN(ID)
);

-- LƯƠNG (tham chiếu đến NHÂN VIÊN)
CREATE TABLE LUONG(
  ID VARCHAR(50) PRIMARY KEY,
  IDNV VARCHAR(50),
  THANG INT NOT NULL,
  NAM INT NOT NULL,
  NGAYTAO DATE NOT NULL,
  SONGAYLAM INT NOT NULL,
  TIENTHUONG DECIMAL(10,2) NOT NULL,
  TIENTROCAP DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (IDNV) REFERENCES NHANVIEN(ID)
);
